CREATE TABLE restaurants (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  nit VARCHAR(20) UNIQUE NOT NULL,
  direccion VARCHAR(200) NOT NULL,
  telefono VARCHAR(13) NOT NULL,
  url_logo VARCHAR(300) NOT NULL,
  owner_user_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
