CREATE TABLE dishes (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  precio DOUBLE NOT NULL,
  descripcion VARCHAR(500) NOT NULL,
  url_imagen VARCHAR(300) NOT NULL,
  categoria VARCHAR(20) NOT NULL,
  restaurant_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
